Comando size + refactors
eliabefranca/eliabot pull request #8
Opened 2021-07-18 02:52 UTC by PierreVieira

## O que esse PR faz?
- Adição de pastas de IDE no .gitignore
- Criação de um package utils
- Remoção de código duplicado
- Comando `.size`

2021-07-18 04:04 UTC, Agronault requested changes
deixei algumas sugestões

2021-07-18 04:04 UTC, Agronault commented on .gitignore
> +.vscode
n coloca pra ignorar n, é lá q configura o debugger pro vscode, isso é útil

2021-07-18 04:04 UTC, Agronault commented on .vscode/launch.json
> -{
deleta n pô

2021-07-18 04:04 UTC, Agronault commented on src/bot/commands/command-list/size.ts
> +export default size
faltou blank line eof

2021-07-18 04:04 UTC, Agronault commented on src/bot/commands/command-list/utils/getContactNumber.ts
> +export default getContactNumber
faltou blank line eof

2021-07-18 04:04 UTC, Agronault commented on src/bot/commands/command-list/utils/getPersonExists.ts
> +export default getPersonExists
faltou blank line eof

2021-07-18 04:04 UTC, Agronault commented on src/bot/commands/command-list/utils/getRandomInterval.ts
> +export default getRandomInterval
blank line eof

2021-07-18 04:04 UTC, Agronault commented on src/bot/commands/command-list/utils/outputErrorMessage.ts
> +export default outputErrorMessage
blank line eof

2021-07-18 04:04 UTC, Agronault commented on src/bot/commands/command-list/utils/validPerson.ts
> +export default validPerson
blank line eof

2021-07-18 04:04 UTC, Agronault commented on src/bot/commands/command-list/kiss.ts
> +  if (kissedPerson != null) {
```suggestion
  if (kissedPerson) {
```

2021-07-18 04:04 UTC, Agronault commented on src/bot/commands/command-list/rank.ts
> +    await client.reply(
não precisa dar await aqui, esse é o fim do fluxo

2021-07-18 04:04 UTC, Agronault commented on src/bot/commands/command-list/size.ts
> +  const piupiu = '8' + '='.repeat(sizePiupiu) + 'D'
acho q é melhor fazer um Math.floor do size/3, pq 10cm ser um pinto "8==========D" não faz sentido

2021-07-18 04:04 UTC, Agronault commented on src/bot/commands/command-list/size.ts
> +  const sizePiupiu = getRandomInterval(2, 20)
vc abandonou aquela ideia de usar o user como seed pra fazer o valor sempre ser o mesmo? Vc pode somar o valor do ASCII dos chars do nome do usuário e fazer o resto da divisão disso por 19 dps somar 2

2021-07-18 04:30 UTC, Eliabe45 commented on .gitignore
> +.vscode
Pior que nem fui eu, provavelmente foi o commit do @julioCROS que eu deixei passar hahaha

2021-07-18 04:31 UTC, Eliabe45 commented on .vscode/launch.json
> -{
Num deletei :sob: , eu uso tbm hahauau

2021-07-18 04:36 UTC, Eliabe45 commented on src/bot/commands/command-list/size.ts
> +export default size
Tinha que criar um .eslintrc e deixar configurado no projeto junto com o prettier, aí bota uns hooks do git pra formatar com o lint-staged, mas mó preguiça. Qqr dia eu faço isso :+1:

2021-07-18 04:51 UTC, Eliabe45 requested changes
Opa, valeu pela contribuição :heart: 

Dá uma olhadinha nesses pontos:


1. Agora os comandos têm categoria, já tá tipado, no caso esse comando é da categoria 'funny', inclui isso no export do comando por favor
2. Tá dando um conflitinho com a main no arquivo do comando .kiss, dá um reset aí no seu arquivo e manda um git pull
2. Consegue exportar o getRandomContactNumber e o validPerson com named export ao invés de default export? Só pra deixar no padrão mesmo
3. N precisa botar o .vscode dentro do .gitignore

2021-07-18 12:54 UTC, PierreVieira commented on src/bot/commands/command-list/size.ts
> +  const sizePiupiu = getRandomInterval(2, 20)
Abandonei não, mas seria só uma v1 do `.size`. Eu entendi a lógica, mas como o pr tinha mais modificações (muita extração de código) achei necessário dar esse merge primeiro para evitar conflitos futuros.

2021-07-18 13:00 UTC, PierreVieira commented on src/bot/commands/command-list/size.ts
> +  const piupiu = '8' + '='.repeat(sizePiupiu) + 'D'
era pra ser
```.ts
 const piupiu = '8' + '='.repeat(sizePiupiu - 2) + 'D'
```
Mas esqueci do -2 na hora hihi.

2021-07-18 13:31 UTC, Agronault commented on src/bot/commands/command-list/size.ts
> +export default size
> Tinha que criar um .eslintrc e deixar configurado no projeto junto com o prettier, aí bota uns hooks do git pra formatar com o lint-staged, mas mó preguiça. Qqr dia eu faço isso 👍

@Eliabe45 vou colocar na priorização aqui, boa xD

2021-07-18 13:33 UTC, Agronault commented on src/bot/commands/command-list/size.ts
> +  const sizePiupiu = getRandomInterval(2, 20)
> Abandonei não, mas seria só uma v1 do `.size`. Eu entendi a lógica, mas como o pr tinha mais modificações (muita extração de código) achei necessário dar esse merge primeiro para evitar conflitos futuros.

Show, boa, vou colocar isso no backlog ent

2021-07-18 13:36 UTC, Agronault commented on src/bot/commands/command-list/size.ts
> +  const piupiu = '8' + '='.repeat(sizePiupiu) + 'D'
oq acha de dividir por 3?
5cm -> 8=D
10cm -> 8===D
20cm -> 8======D

2021-07-19 00:58 UTC, Eliabe45 approved these changes
Perfeito :heart: 

Excelente contribuição, melhorou muito a legibilidade :smile:

2021-07-19 00:58 UTC, merged